### ISSUE TITLE
NameError: name 'BINARY' is not defined NameError: name 'INTEGER' is not defined

### ISSUE THREAD

**Issue by avelin0** [tuliotoffolo/fstsp#4]
no arquivo fstsp.py apresentava esse problema:

```
python fstsp.py data/5a
solutions\5a.txt
Traceback (most recent call last):
  File "C:\Users\avelino\fstsp\fstsp-python\fstsp.py", line 252, in <module>
    formulation = CompactFormulation(inst, murray_rules=arg.murray_rules)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\avelino\fstsp\fstsp-python\fstsp.py", line 54, in __init__
    x = {(i, j, ell): model.add_var(obj=0, var_type=BINARY,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\avelino\fstsp\fstsp-python\fstsp.py", line 54, in <dictcomp>
    x = {(i, j, ell): model.add_var(obj=0, var_type=BINARY,
                                                    ^^^^^^
NameError: name 'BINARY' is not defined
```

adicionando  `from mip import BINARY` resolveu o problema

**Comment by avelin0** [comment]
no arquivo  murray_fstsp.py apresentava esse problema:

```
python murray_fstsp.py data/5b
solutions\murray_5b.txt
Traceback (most recent call last):
  File "C:\Users\avelino\fstsp\fstsp-python\murray_fstsp.py", line 278, in <module>
    formulation = MurrayFormulation(inst)
                  ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\avelino\fstsp\fstsp-python\murray_fstsp.py", line 25, in __init__
    x = {(i, j): model.add_var(obj=0, var_type=BINARY,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\avelino\fstsp\fstsp-python\murray_fstsp.py", line 25, in <dictcomp>
    x = {(i, j): model.add_var(obj=0, var_type=BINARY,
                                               ^^^^^^
NameError: name 'BINARY' is not defined
```

```
python murray_fstsp.py data/5b
solutions\murray_5b.txt

Traceback (most recent call last):
  File "C:\Users\avelino\fstsp\fstsp-python\murray_fstsp.py", line 278, in <module>
    formulation = MurrayFormulation(inst)
                  ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\avelino\fstsp\fstsp-python\murray_fstsp.py", line 33, in __init__
    u = {i: model.add_var(obj=0, var_type=INTEGER, lb=1, ub=len(inst.V_) + 2,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\avelino\fstsp\fstsp-python\murray_fstsp.py", line 33, in <dictcomp>
    u = {i: model.add_var(obj=0, var_type=INTEGER, lb=1, ub=len(inst.V_) + 2,
                                          ^^^^^^^
NameError: name 'INTEGER' is not defined
```

adicionando `from mip import BINARY, INTEGER` resolveu esse problema
